### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [3]:
#Declare the function
def Ex1(s,i,j):
    return s[i:j],len(s)

#Call the function
s = "Hello World !"
a = Ex1(s,3,8)[0]
b = Ex1(s,3,8)[1]

#print the result in a well formated format
print("Here is the sliced string \"{}\" and the length of the string is {}".format(a,b))

Here is the sliced string "lo Wo" and the length of the string is 13


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [4]:
#Declare the function
def Ex2(x,y):
    return x+y

#Call with the values 1 and two
a = Ex2(1,2.1)
print(a)

#Check the type of the result
print(type(a))

#Call with the values False and 2
a = Ex2(False,2)
print(a)

#Check the type of the result
print(type(a))

3.1
<class 'float'>
2
<class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [3]:
#Declare the function

s = "Hello World !"

d = {k:s.count(k) for k in s }

print(d)

{'H': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 2, 'W': 1, 'r': 1, 'd': 1, '!': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [9]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

ModuleNotFoundError: No module named 'lib'

In [11]:
a = [1,2,3]
b = [1,2,3]


for i,j in zip(a,b[::-1]):
    print(i,j)

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [39]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)
#Try to print input
c = np.zeros((2,10))
np.concatenate((a,b),1,c)

#concatenate horizontally
#output should look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])





array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [2]:
import numpy as np

a = np.arange(3)
b = np.ones((3,3,3))

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
c = np.repeat(a,3)
d = np.concatenate((a,a,a))
e = np.concatenate((c,d))

print(e)

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],
#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],
#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])

e = a + b

print(e)
#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

e = b.reshape(3,9)

print(e)

[0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
